[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 30

[character]
success_symbol = "[Â»](bold green) "
error_symbol = "[Â»](bold red) "

[aws]
disabled = true

[cmd_duration]
format = "âŒ›ï¸ [$duration]($style)"
show_notifications = true
min_time_to_notify = 120_000

[hostname]
ssh_only = false
format = "îœ‘ "